// <auto-generated />
using HumanResourcesDepartment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanResourcesDepartment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230518122625_secondMigration")]
    partial class secondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanResourcesDepartment.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BirthYear")
                        .HasColumnType("int");

                    b.Property<int>("EmploymentYear")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthYear = 1980,
                            EmploymentYear = 2010,
                            FullName = "Pera Peric",
                            Role = "Direktor",
                            Salary = 3000m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            BirthYear = 1985,
                            EmploymentYear = 2011,
                            FullName = "Mika Mikic",
                            Role = "Sekretar",
                            Salary = 1000m,
                            UnitId = 1
                        },
                        new
                        {
                            Id = 3,
                            BirthYear = 1981,
                            EmploymentYear = 2012,
                            FullName = "Iva Ivic",
                            Role = "Računovođa",
                            Salary = 2000m,
                            UnitId = 2
                        },
                        new
                        {
                            Id = 4,
                            BirthYear = 1982,
                            EmploymentYear = 2013,
                            FullName = "Zika Zikic",
                            Role = "Inženjer",
                            Salary = 2500m,
                            UnitId = 3
                        },
                        new
                        {
                            Id = 5,
                            BirthYear = 1984,
                            EmploymentYear = 2014,
                            FullName = "Ana Anic",
                            Role = "Inženjer",
                            Salary = 2500m,
                            UnitId = 3
                        });
                });

            modelBuilder.Entity("HumanResourcesDepartment.Models.OrganizationalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstablishmentYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("OrganizationalUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstablishmentYear = 2010,
                            Name = "Administracija"
                        },
                        new
                        {
                            Id = 2,
                            EstablishmentYear = 2012,
                            Name = "Računovodstvo"
                        },
                        new
                        {
                            Id = 3,
                            EstablishmentYear = 2013,
                            Name = "Razvoj"
                        });
                });

            modelBuilder.Entity("HumanResourcesDepartment.Models.Employee", b =>
                {
                    b.HasOne("HumanResourcesDepartment.Models.OrganizationalUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });
#pragma warning restore 612, 618
        }
    }
}
